# Generated by Django 3.0.7 on 2020-08-05 12:37

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion
import imagekit.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, unique=True, verbose_name='Azərbaycanca Başlıq')),
                ('title_english', models.CharField(max_length=100, unique=True, verbose_name='İngiliscə Başlıq')),
                ('content', ckeditor.fields.RichTextField(verbose_name='Azərbaycanca Kontent')),
                ('content_english', ckeditor.fields.RichTextField(verbose_name='Ingiliscə Kontent')),
                ('slug', models.SlugField(blank=True, default='', unique=True, verbose_name='Link')),
                ('cover_image', imagekit.models.fields.ProcessedImageField(blank=True, null=True, upload_to='article/cover/', verbose_name='Qapaq Şəkli')),
                ('pub_date', models.DateTimeField(auto_now_add=True, verbose_name='Paylaşılma Tarixi')),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, unique=True, verbose_name='Azərbaycanca Başlıq')),
                ('title_english', models.CharField(max_length=50, unique=True, verbose_name='İngiliscə Başlıq')),
                ('slug', models.SlugField(blank=True, default='', unique=True, verbose_name='Link')),
            ],
        ),
        migrations.CreateModel(
            name='ArticleImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', imagekit.models.fields.ProcessedImageField(upload_to='article/images/', verbose_name='Şəkil')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.Article')),
            ],
        ),
        migrations.AddField(
            model_name='article',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='blog.Category', verbose_name='Kategoriya'),
        ),
    ]
