# Generated by Django 3.0.7 on 2020-09-01 07:11

from django.db import migrations
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20200808_2217'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='main_image',
            field=imagekit.models.fields.ProcessedImageField(blank=True, null=True, upload_to='article/main_iamges', verbose_name='Əsas şəkil'),
        ),
    ]
