# Generated by Django 3.0.7 on 2020-09-01 12:26

from django.db import migrations
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_article_main_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='main_image',
            field=imagekit.models.fields.ProcessedImageField(blank=True, null=True, upload_to='article/main_images', verbose_name='Əsas şəkil'),
        ),
    ]
