# Generated by Django 3.0.7 on 2020-09-09 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20200901_1626'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='slug',
            field=models.SlugField(blank=True, default='', verbose_name='Link'),
        ),
        migrations.AlterField(
            model_name='article',
            name='title',
            field=models.CharField(max_length=100, verbose_name='Azərbaycanca Başlıq'),
        ),
        migrations.AlterField(
            model_name='article',
            name='title_english',
            field=models.CharField(max_length=100, verbose_name='İngiliscə Başlıq'),
        ),
    ]
