# Generated by Django 3.0.7 on 2020-09-12 16:00

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20200912_1955'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='blog.Category', verbose_name='Kategoriya'),
        ),
        migrations.AlterField(
            model_name='article',
            name='content',
            field=ckeditor.fields.RichTextField(verbose_name='Azərbaycanca Kontent *'),
        ),
        migrations.AlterField(
            model_name='article',
            name='main_image',
            field=imagekit.models.fields.ProcessedImageField(blank=True, upload_to='article/main_images', verbose_name='Əsas şəkil *'),
        ),
        migrations.AlterField(
            model_name='category',
            name='title',
            field=models.CharField(max_length=50, unique=True, verbose_name='Azərbaycanca Başlıq *'),
        ),
    ]
