# Generated by Django 3.0.11 on 2021-02-01 14:41

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20200912_2000'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='blog.Category', verbose_name='Kategoriya *'),
        ),
        migrations.AlterField(
            model_name='article',
            name='content_english',
            field=ckeditor.fields.RichTextField(null=True, verbose_name='Ingiliscə Kontent'),
        ),
        migrations.AlterField(
            model_name='article',
            name='title',
            field=models.CharField(max_length=100, verbose_name='Azərbaycanca Başlıq *'),
        ),
        migrations.AlterField(
            model_name='article',
            name='title_english',
            field=models.CharField(max_length=100, null=True, verbose_name='İngiliscə Başlıq *'),
        ),
    ]
