# Generated by Django 3.0.11 on 2021-02-01 14:47

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_auto_20210201_1841'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='content',
            field=ckeditor.fields.RichTextField(blank=True, verbose_name='Azərbaycanca Kontent *'),
        ),
        migrations.AlterField(
            model_name='article',
            name='title_english',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='İngiliscə Başlıq *'),
        ),
    ]
