# Generated by Django 3.0.11 on 2021-02-01 14:48

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_auto_20210201_1847'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='content',
            field=ckeditor.fields.RichTextField(verbose_name='Azərbaycanca Kontent *'),
        ),
        migrations.AlterField(
            model_name='article',
            name='content_english',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Ingiliscə Kontent'),
        ),
    ]
