# Generated by Django 3.0.11 on 2021-07-22 06:49

from django.db import migrations, models
import django.db.models.deletion
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_auto_20210306_1759'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='show',
            field=models.BooleanField(default=False, verbose_name='Göstərilsin'),
        ),
        migrations.AddField(
            model_name='category',
            name='cover',
            field=imagekit.models.fields.ProcessedImageField(blank=True, null=True, upload_to='category/cover/', verbose_name='Qapaq Şəkli'),
        ),
        migrations.AlterField(
            model_name='article',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='blog.Category', verbose_name='Kateqoriya *'),
        ),
    ]
